# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/ruby
pool:
  vmImage: 'ubuntu-latest' # other options: 'macOS-latest', 'windows-latest'

steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.7'
      addToPath: true
  - script: |
      CALL gem install bundler
      bundle install --retry=3 --jobs=4
    displayName: 'bundle install'
  - script: bundle exec rake
    displayName: 'bundle exec rake'
