# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: id3tag 0.5.4 ruby lib

Gem::Specification.new do |s|
  s.name = "id3tag"
  s.version = "0.5.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Krists Ozols"]
  s.date = "2013-12-28"
  s.description = "Native Ruby ID3 tag reader that aims for 100% covarage of ID3v2.x and ID3v1.x standards"
  s.email = "krists@iesals.lv"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "id3tag.gemspec",
    "lib/id3tag.rb",
    "lib/id3tag/audio_file.rb",
    "lib/id3tag/frame_id_advisor.rb",
    "lib/id3tag/frames/util/genre_names.rb",
    "lib/id3tag/frames/v1/comments_frame.rb",
    "lib/id3tag/frames/v1/genre_frame.rb",
    "lib/id3tag/frames/v1/text_frame.rb",
    "lib/id3tag/frames/v1/track_nr_frame.rb",
    "lib/id3tag/frames/v2/basic_frame.rb",
    "lib/id3tag/frames/v2/comments_frame.rb",
    "lib/id3tag/frames/v2/frame_fabricator.rb",
    "lib/id3tag/frames/v2/frame_flags.rb",
    "lib/id3tag/frames/v2/genre_frame.rb",
    "lib/id3tag/frames/v2/genre_frame/genre_parser.rb",
    "lib/id3tag/frames/v2/genre_frame/genre_parser_24.rb",
    "lib/id3tag/frames/v2/genre_frame/genre_parser_pre_24.rb",
    "lib/id3tag/frames/v2/involved_people_list_frame.rb",
    "lib/id3tag/frames/v2/private_frame.rb",
    "lib/id3tag/frames/v2/text_frame.rb",
    "lib/id3tag/frames/v2/unique_file_id_frame.rb",
    "lib/id3tag/frames/v2/unsychronized_transcription_frame.rb",
    "lib/id3tag/frames/v2/user_text_frame.rb",
    "lib/id3tag/id3_v1_frame_parser.rb",
    "lib/id3tag/id3_v2_frame_parser.rb",
    "lib/id3tag/id3_v2_tag_header.rb",
    "lib/id3tag/number_util.rb",
    "lib/id3tag/scope.rb",
    "lib/id3tag/string_util.rb",
    "lib/id3tag/synchsafe_integer.rb",
    "lib/id3tag/tag.rb",
    "lib/id3tag/unsynchronization.rb",
    "spec/features/can_read_non_audio_files_spec.rb",
    "spec/features/can_read_tag_v1_spec.rb",
    "spec/fixtures/id3v1_and_v2.mp3",
    "spec/fixtures/id3v1_with_track_nr.mp3",
    "spec/fixtures/id3v1_without_track_nr.mp3",
    "spec/fixtures/id3v2.mp3",
    "spec/fixtures/pov_20131018-2100a.mp3.v1_tag_body",
    "spec/fixtures/pov_20131018-2100a.mp3.v2_3_tag_body",
    "spec/fixtures/signals_1.mp3.v2_3_tag_body",
    "spec/id3tag_extract_tags",
    "spec/lib/id3tag/audio_file_spec.rb",
    "spec/lib/id3tag/frames/util/genre_name_by_id_finder_spec.rb",
    "spec/lib/id3tag/frames/v1/comments_frame_spec.rb",
    "spec/lib/id3tag/frames/v1/genre_frame_spec.rb",
    "spec/lib/id3tag/frames/v1/text_frame_spec.rb",
    "spec/lib/id3tag/frames/v1/track_nr_frame_spec.rb",
    "spec/lib/id3tag/frames/v2/basic_frame_spec.rb",
    "spec/lib/id3tag/frames/v2/comments_frame_spec.rb",
    "spec/lib/id3tag/frames/v2/frame_fabricator_spec.rb",
    "spec/lib/id3tag/frames/v2/frame_flags_spec.rb",
    "spec/lib/id3tag/frames/v2/genre_frame/genre_parser_24_spec.rb",
    "spec/lib/id3tag/frames/v2/genre_frame/genre_parser_pre_24_spec.rb",
    "spec/lib/id3tag/frames/v2/genre_frame/genre_parser_spec.rb",
    "spec/lib/id3tag/frames/v2/genre_frame_spec.rb",
    "spec/lib/id3tag/frames/v2/text_frame_spec.rb",
    "spec/lib/id3tag/frames/v2/unique_file_id_frame_spec.rb",
    "spec/lib/id3tag/frames/v2/user_text_frame_spec.rb",
    "spec/lib/id3tag/id3_v1_frame_parser_spec.rb",
    "spec/lib/id3tag/id3_v2_frame_parser_spec.rb",
    "spec/lib/id3tag/id3_v2_tag_header_spec.rb",
    "spec/lib/id3tag/id3tag_spec.rb",
    "spec/lib/id3tag/number_util_spec.rb",
    "spec/lib/id3tag/string_util_spec.rb",
    "spec/lib/id3tag/synchsafe_integer_spec.rb",
    "spec/lib/id3tag/tag_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/mp3_fixtures.rb",
    "standard_documents/id3v2-00.txt",
    "standard_documents/id3v2.3.0.txt",
    "standard_documents/id3v2.4.0-frames.txt",
    "standard_documents/id3v2.4.0-structure.txt"
  ]
  s.homepage = "http://github.com/krists/id3tag"
  s.licenses = ["MIT"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.2")
  s.rubygems_version = "2.2.0"
  s.summary = "Native Ruby ID3 tag reader that aims for 100% covarage of ID3v2.x and ID3v1.x standards"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<rspec>, ["~> 2.13.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<coveralls>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<rspec>, ["~> 2.13.0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<coveralls>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<rspec>, ["~> 2.13.0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<coveralls>, [">= 0"])
  end
end

